version: "3"
services:
  app:
    container_name: express
    restart: always
    build: ./
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    entrypoint: npm install && nodemon server.js
