version: "3"
services:
  app:
    container_name: express
    restart: always
    build: ./
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && nodemon server.js"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
  nginx:
    image: nginx:alpine
    ports:
      - 8082:80
    volumes:
      - ./nginx/src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - react
  react:
    container_name: react
    restart: always
    build: ./
    volumes:
      - ./client:/app
    entrypoint: /bin/sh -c "npm install && npm run start"
