version: "3"
services:
  app:
    container_name: express
    restart: always
    build: ./
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && nodemon server.js"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
    # ports:
      # - 27018:27018
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
